#! /bin/bash
echo -e "[1] Run all tests  [2] Run a specific test "
echo -n "=> "
read resp
case "$resp" in
   1|1|"")
      "vendor/bin/codecept" "run" "tests/functional/Pessoa" "--steps"
      "vendor/bin/codecept" "run" "tests/functional/Imovel" "--steps"
      "vendor/bin/codecept" "run" "tests/functional/ImovelDelete" "--steps"
      "vendor/bin/codecept" "run" "tests/functional/PessoaDelete" "--steps"
   ;;
   2|2)
      echo -e "Enter test path"
      echo -n "=> "
      read resp
      "vendor/bin/codecept" "run" "$resp"
   ;;
esac